name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    # if: contains(github.event.head_commit.message, 'release')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Get current version
        id: package-version
        run: echo ::set-output name=current-version::$(cargo pkgid | cut -d# -f2 | cut -d: -f2)
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: target/release/ghl
          generateReleaseNotes: true
          makeLatest: true
          name: ghl v${{ steps.package-version.outputs.current-version }}
          tag: ghl-v${{ steps.package-version.outputs.current-version }}
